services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GIN_MODE=release
      - PORT=3000
      - DATABASE_URL=host=db user=postgres password=sekret dbname=pismo_backend_development port=5432 sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sekret
      POSTGRES_DB: pismo_backend_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pismo_backend_development"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:
